version: '3'
services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:mariadb://db:3306/pf?createDatabaseIfNotExist=true
    # it may fail on first try, as db needs some time to start working.
    # tried healthcheck and stuff, but nothing really worked well.
    restart: on-failure
  db:
    image: mariadb
    restart: always
    environment:
      CHARACTER_SET_SERVER: utf8
      COLLATION_SERVER: utf8_general_ci
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: pf
    ports:
      - "3306:3306"
