version: '3'
services:
#  even with depends_on and links and WAIT_HOSTS app can still be build too fast
#  maybe just try restarting it like 3 times on startup?
#  I need to read up on solutions to this problem
  app:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    links:
      - db:pf
    environment:
      - WAIT_HOSTS=db:3306
      - SPRING.DATASOURCE.URL=jdbc:mariadb://db:3306/pf?createDatabaseIfNotExist=true
  db:
    image: mariadb
    restart: always
    environment:
      CHARACTER_SET_SERVER: utf8
      COLLATION_SERVER: utf8_general_ci
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: pf
    ports:
      - "3306:3306"
