name: Dependency Review

on: [pull_request_target]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create container
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
