name: Dependency Review
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Create container
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
