name: Maven - build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: pf
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Shutdown default Ubuntu MySQL
        run: sudo service mysql stop
      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mariadb version: 'latest'
          mysql database: 'pf'
          mysql root password: root # for now, later will be: ${{ secrets.RootPassword }}
          mysql user: 'root'
      - name: Create container
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      - name: Run UnitTests
        run: mvn -Dtest=com/pbuczek/pf/UnitTests.java test
      - name: Run ApplicationTests
        run: mvn -Dtest=com/pbuczek/pf/ApplicationTests.java test
      - name: Run IntegrationTests
        run: mvn -Dtest=com/pbuczek/pf/IntegrationTests.java test
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          ignore-maven-wrapper: true
