name: Maven - build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: pf
      DB_USER: root
      DB_PASSWORD: root
    strategy:
      matrix:
        language: [ 'java' ]
    steps:
      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mariadb version: 'latest'
          mysql database: 'pf'
          mysql root password: root # for now, later will be: ${{ secrets.RootPassword }}
          mysql user: 'root'
      - name: Create container
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      - name: Run UnitTests
        run: mvn -Dtest=com/pbuczek/pf/UnitTests.java test
      - name: Run IntegrationTests
        run: mvn -Dtest=com/pbuczek/pf/IntegrationTests.java test
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild codeql
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"


